behaviors:
  Pyramids:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 10240
      learning_rate: 0.0001121825928129903
      beta: 0.0026687020150654057
      epsilon: 0.22272536971010667
      lambd: 0.9032647969383677
      num_epoch: 7
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 642
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9731863650103103
        strength: 1.0
      curiosity:
        gamma: 0.99
        encoding_size: 0.2
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 890059
    time_horizon: 512
    summary_freq: 10000
