behaviors:
  Worm:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 4096
      learning_rate: 0.00012274041451544002
      beta: 0.0040043697742146635
      epsilon: 0.2936358514023935
      lambd: 0.9324153147140676
      num_epoch: 9
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 913
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9414702019018489
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 886040
    time_horizon: 128
    summary_freq: 10000
