behaviors:
  Basic:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 0.00032753504986696597
      beta: 0.008781267394190665
      epsilon: 0.14131281326786885
      lambd: 0.9507375387709587
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 116
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.8412317278734667
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 697831
    time_horizon: 512
    summary_freq: 10000
