behaviors:
  Walker:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 837265
      learning_rate: 0.00024703219599382783
      buffer_init_steps: 10000
      tau: 0.006207338448835557
      steps_per_update: 5
      save_replay_buffer: false
      init_entcoef: 0.9236647824582087
      reward_signal_steps_per_update: 20
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 836
      num_layers: 5
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9419906983887463
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 321052
    time_horizon: 1535
    summary_freq: 95164
