behaviors:
  Worm:
    trainer_type: sac
    hyperparameters:
      batch_size: 256
      buffer_size: 617579
      learning_rate: 0.0002827613326980117
      buffer_init_steps: 5000
      tau: 0.00794475491833441
      steps_per_update: 5
      save_replay_buffer: false
      init_entcoef: 0.6667105444479261
      reward_signal_steps_per_update: 20
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 352
      num_layers: 5
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.8591200403532053
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 418455
    time_horizon: 1520
    summary_freq: 91900
