behaviors:
  BigWallJump:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.00022665681359329605
      beta: 0.008237220699331292
      epsilon: 0.26506084495221416
      lambd: 0.9102079243501647
      num_epoch: 9
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 908
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.8459106011256784
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 882945
    time_horizon: 512
    summary_freq: 10000
  SmallWallJump:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 10240
      learning_rate: 0.00040609374481184664
      beta: 0.0012041287316743518
      epsilon: 0.1682097233558593
      lambd: 0.9480418675781932
      num_epoch: 8
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 940
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9891477465458094
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 713535
    time_horizon: 256
    summary_freq: 10000
