behaviors:
  BigWallJump:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.0005107266720156973
      beta: 0.008809847578680346
      epsilon: 0.26182212369784263
      lambd: 0.9065429225951188
      num_epoch: 10
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 561
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.8805735389834585
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 662666
    time_horizon: 256
    summary_freq: 10000
  SmallWallJump:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 8192
      learning_rate: 0.00033995357717793066
      beta: 0.001173360317763727
      epsilon: 0.24252338791523656
      lambd: 0.9710646040444099
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 178
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.8488760671470632
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 649349
    time_horizon: 64
    summary_freq: 10000
